# -*- coding: utf-8 -*-
"""DesafioDio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wOqU5isBy2lygsb-WhJF72hpMiWBKFR
"""

!pip install -q -U google-generativeai

import google.generativeai as genai
from google.colab import userdata
import time

try:
    api_key_ia = userdata.get('key_iastudio')
    genai.configure(api_key=api_key_ia)
    print("✅ Chave configurada com sucesso!")
except Exception as e:
    print(f"❌ Erro na chave: {e}")

# 3. EXTRACT
usuarios = [
    {"id": 1, "nome": "Naruto", "news": ""},
    {"id": 2, "nome": "Hinata", "news": ""},
    {"id": 3, "nome": "Sasuke", "news": ""}
]

# 4. TRANSFORM
print("\n🤖 Iniciando geração de mensagens...\n")

def gerar_mensagem_google(usuario):
    try:
        model = genai.GenerativeModel('gemini-2.5-flash')
        response = model.generate_content(
            f"Você é um professor de tecnologia. Crie uma frase curta (max 15 palavras) para {usuario['nome']} sobre a importância de estudar ciência de dados em 2026."
        )
        return response.text
    except Exception as e:
        return f"Erro ao gerar: {e}"

for usuario in usuarios:
    msg = gerar_mensagem_google(usuario)
    usuario['news'] = msg
    print(f"✅ Gerado para {usuario['nome']}!")
    time.sleep(2)

# 5. LOAD
print("\n--- 📊 RESULTADO FINAL ---")
for u in usuarios:
    print(f"Aluno: {u['nome']}")
    print(f"Conselho: {u['news']}")
    print("-" * 30)