# -*- coding: utf-8 -*-
"""DesafioDio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wOqU5isBy2lygsb-WhJF72hpMiWBKFR
"""

!pip install openai

import openai
from google.colab import userdata


key = userdata.get('openai_secret')
client = openai.OpenAI(api_key=key)

usuarios = [
    {"id": 1, "nome": "Naruto", "news": ""},
    {"id": 2, "nome": "Hinata", "news": ""},
    {"id": 3, "nome": "Sasuke", "news": ""},
]


def gerar_mensagem(usuario):
    try:
        completion = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "Você é um professor de tecnologia."},
                {"role": "user", "content": f"Crie uma frases motivacionais para os alunos {usuario['nome']} estudarem sobre tecnologia em 2026."}
            ]
        )
        return completion.choices[0].message.content
    except Exception as e:
        return f"Erro: {e}"

for usuario in usuarios:
    msg = gerar_mensagem(usuario)
    usuario['news'] = msg
    print(f"Mensagem criada para {usuario['nome']}")


print("\n--- RESULTADO FINAL ---")
for u in usuarios:
    print(f"Cliente: {u['nome']} | Mensagem: {u['news']}")